version: '3.8'

services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: hong
      MYSQL_PASSWORD: hong
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: express-demo
      TZ: 'Asia/Seoul'
    volumes:
      - hong-express-mysqldb:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../db/migrations/V1__init.sql:/docker-entrypoint-initdb.d/V1__init.sql
      - ../db/data/afterMigrate.sql:/docker-entrypoint-initdb.d/afterMigrate.sql

volumes:
  hong-express-mysqldb:
